data_ingestion:
  train_data_path: "artifacts/train.csv"
  test_data_path: "artifacts/test.csv"

data_transformation:
  processor_obj_path: "artifacts/preprocessor.pkl"

model:
  model_path: "artifacts/model.pkl"